#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on

echo "Displaying all active IPv4 IPs..."
ip addr show | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}$' | `grep -v '127\.'` | awk '{print $2}'

echo "Done."
